# Generated by Django 5.1.6 on 2025-02-28 15:40

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_alter_organization_id"),
        ("people", "0004_alter_people_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid_utils.compat.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="organizations.organization",
                    ),
                ),
                ("team", models.ManyToManyField(blank=True, related_name="projects", to="people.people")),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "Projects",
            },
        ),
    ]
