# Generated by Django 5.1.6 on 2025-02-28 15:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, verbose_name="name")),
            ],
            options={
                "verbose_name": "people",
                "verbose_name_plural": "people",
                "ordering": ["id"],
            },
        ),
    ]
